// Service Worker — immutable, verified release assets. Generated by build-release.cjs.
const VERSION_TAG = '2026.10.05A';
const APP_SCOPE = new URL(self.registration.scope);
const CACHE_PREFIX = `ledger-scope-v1|${encodeURIComponent(APP_SCOPE.href)}|`;
const CACHE_NAME = `${CACHE_PREFIX}${VERSION_TAG}|cache`;
const ASSET_MANIFEST = [
  {
    "path": "./",
    "sha256": "17f5daf90b21868a7d8242ad3c5876456f5e7631ce39cf3d26d330d471ed5aec",
    "types": [
      "text/html"
    ]
  },
  {
    "path": "./index.html",
    "sha256": "17f5daf90b21868a7d8242ad3c5876456f5e7631ce39cf3d26d330d471ed5aec",
    "types": [
      "text/html"
    ]
  },
  {
    "path": "./manifest.json",
    "sha256": "d64248ede0a2103b5481d305f9d90cc99fe0f5c61df3249b3d06a0b9455fc3cc",
    "types": [
      "application/json",
      "application/manifest+json"
    ]
  },
  {
    "path": "./icon-192.png",
    "sha256": "0dd656426b63989a08ea5147b3312100a99893c956fabd21e03214a82f2319c2",
    "types": [
      "image/png"
    ]
  },
  {
    "path": "./icon-512.png",
    "sha256": "803b6953f5fd0651e44f60c3a847387425e96961499ed80713b926c1ccc952af",
    "types": [
      "image/png"
    ]
  },
  {
    "path": "./icon-180.png",
    "sha256": "461d7f14b0bc1160ebc1fb3be838037f9979ad400a0aa7efbc59b270d84209a9",
    "types": [
      "image/png"
    ]
  }
];
const APP_ASSETS = new Map(ASSET_MANIFEST.map(asset => [new URL(asset.path, APP_SCOPE).href, asset]));

function assetFailure(kind) {
  return Object.assign(new Error(kind === 'network' ? 'Asset network unavailable' : 'Asset verification failed'), { kind });
}
async function fetchVerifiedAsset(url, asset) {
  let response;
  try { response = await fetch(new Request(url, { cache: 'reload', credentials: 'same-origin', redirect: 'follow' })); }
  catch (_) { throw assetFailure('network'); }
  if (!response || response.status !== 200 || response.redirected) throw assetFailure('integrity');
  const type = (response.headers.get('content-type') || '').split(';')[0].trim().toLowerCase();
  if (!asset.types.includes(type)) throw assetFailure('integrity');
  let bytes;
  try { bytes = await response.clone().arrayBuffer(); }
  catch (_) { throw assetFailure('network'); }
  let digest;
  try {
    const raw = await crypto.subtle.digest('SHA-256', bytes);
    digest = Array.from(new Uint8Array(raw), byte => byte.toString(16).padStart(2, '0')).join('');
  } catch (_) { throw assetFailure('integrity'); }
  if (digest !== asset.sha256) throw assetFailure('integrity');
  return response;
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    // Validate every response before opening/writing this release cache.
    const validated = await Promise.all([...APP_ASSETS].map(async ([url, asset]) =>
      ({ url, response: await fetchVerifiedAsset(url, asset) })));
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(validated.map(({ url, response }) => cache.put(url, response)));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    // Preserve legacy, different-scope, current and future-version caches.
    try {
      const keys = await caches.keys();
      await Promise.all(keys.filter(key => {
        if (!key.startsWith(CACHE_PREFIX)) return false;
        const match = key.slice(CACHE_PREFIX.length).match(/^(\d{4}\.\d{2}\.\d{2}[A-Z])\|cache$/);
        return match && match[1] < VERSION_TAG;
      }).map(key => caches.delete(key).catch(() => false)));
    } catch (_) {}
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || req.headers.has('range')) return;
  const url = new URL(req.url);
  if (!/^https?:$/.test(url.protocol) || url.origin !== APP_SCOPE.origin) return;
  url.search = ''; url.hash = '';
  const canonical = url.href, asset = APP_ASSETS.get(canonical);
  if (!asset) return;
  const task = (async () => {
    const cached = await caches.match(canonical, { cacheName: CACHE_NAME }).catch(() => undefined);
    // No background overwrite: a cached release stays fixed until a new worker installs.
    if (cached) return { response: cached, stored: Promise.resolve() };
    try {
      const response = await fetchVerifiedAsset(canonical, asset);
      const cacheResponse = response.clone();
      const stored = caches.open(CACHE_NAME).then(cache => cache.put(canonical, cacheResponse)).catch(() => {});
      return { response, stored };
    } catch (error) {
      const offline = error.kind === 'network';
      return { response: new Response(offline
        ? '目前無法連線，且缺少本版本的離線檔案。請連線後重新開啟。'
        : '網站檔案尚未完整更新，本次未載入其他版本。請稍後重新開啟。', {
        status: offline ? 504 : 503, statusText: offline ? 'Offline' : 'Release unavailable',
        headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' },
      }), stored: Promise.resolve() };
    }
  })();
  event.respondWith(task.then(result => result.response));
  event.waitUntil(task.then(result => result.stored));
});
